// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

/// Pigeon equivalent of VideoViewType.
typedef NS_ENUM(NSUInteger, PlatformVideoViewType) {
  PlatformVideoViewTypeTextureView = 0,
  PlatformVideoViewTypePlatformView = 1,
};

/// Wrapper for PlatformVideoViewType to allow for nullability.
@interface PlatformVideoViewTypeBox : NSObject
@property(nonatomic, assign) PlatformVideoViewType value;
- (instancetype)initWithValue:(PlatformVideoViewType)value;
@end

@class PlatformVideoViewCreationParams;
@class VideoPlayerOptions;
@class CreateMessage;

/// Information passed to the platform view creation.
@interface PlatformVideoViewCreationParams : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPlayerId:(NSInteger )playerId;
@property(nonatomic, assign) NSInteger  playerId;
@end

/// Additional buffering and playback options for Android/iOS players.
@interface VideoPlayerOptions : NSObject
+ (instancetype)makeWithMixWithOthers:(nullable NSNumber *)mixWithOthers
    allowBackgroundPlayback:(nullable NSNumber *)allowBackgroundPlayback
    minBufferMs:(nullable NSNumber *)minBufferMs
    maxBufferMs:(nullable NSNumber *)maxBufferMs
    bufferForPlaybackMs:(nullable NSNumber *)bufferForPlaybackMs
    bufferForPlaybackAfterRebufferMs:(nullable NSNumber *)bufferForPlaybackAfterRebufferMs;
/// mix audio with other sources? (old default = false)
@property(nonatomic, strong, nullable) NSNumber * mixWithOthers;
/// keep playing when app is backgrounded? (default = false)
@property(nonatomic, strong, nullable) NSNumber * allowBackgroundPlayback;
/// min buffer in ms before playback starts
@property(nonatomic, strong, nullable) NSNumber * minBufferMs;
/// max buffer in ms to retain
@property(nonatomic, strong, nullable) NSNumber * maxBufferMs;
/// buffer in ms required to start playback
@property(nonatomic, strong, nullable) NSNumber * bufferForPlaybackMs;
/// buffer in ms required after a rebuffer event
@property(nonatomic, strong, nullable) NSNumber * bufferForPlaybackAfterRebufferMs;
@end

@interface CreateMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAsset:(nullable NSString *)asset
    uri:(nullable NSString *)uri
    packageName:(nullable NSString *)packageName
    formatHint:(nullable NSString *)formatHint
    httpHeaders:(NSDictionary<NSString *, NSString *> *)httpHeaders
    viewType:(nullable PlatformVideoViewTypeBox *)viewType
    options:(nullable VideoPlayerOptions *)options;
@property(nonatomic, copy, nullable) NSString * asset;
@property(nonatomic, copy, nullable) NSString * uri;
@property(nonatomic, copy, nullable) NSString * packageName;
@property(nonatomic, copy, nullable) NSString * formatHint;
@property(nonatomic, copy) NSDictionary<NSString *, NSString *> * httpHeaders;
@property(nonatomic, strong, nullable) PlatformVideoViewTypeBox * viewType;
@property(nonatomic, strong, nullable) VideoPlayerOptions * options;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetMessagesCodec(void);

@protocol AndroidVideoPlayerApi
- (void)initializeWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)createMsg:(CreateMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
- (void)disposePlayerId:(NSInteger)playerId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setLoopingPlayerId:(NSInteger)playerId looping:(BOOL)looping error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setVolumePlayerId:(NSInteger)playerId volume:(double)volume error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setPlaybackSpeedPlayerId:(NSInteger)playerId speed:(double)speed error:(FlutterError *_Nullable *_Nonnull)error;
- (void)playPlayerId:(NSInteger)playerId error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)positionPlayerId:(NSInteger)playerId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)seekToPlayerId:(NSInteger)playerId position:(NSInteger)position error:(FlutterError *_Nullable *_Nonnull)error;
- (void)pausePlayerId:(NSInteger)playerId error:(FlutterError *_Nullable *_Nonnull)error;
- (void)setMixWithOthersMixWithOthers:(BOOL)mixWithOthers error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpAndroidVideoPlayerApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AndroidVideoPlayerApi> *_Nullable api);

extern void SetUpAndroidVideoPlayerApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AndroidVideoPlayerApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
