// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Messages.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

/// Pigeon equivalent of VideoViewType.
@implementation PlatformVideoViewTypeBox
- (instancetype)initWithValue:(PlatformVideoViewType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface PlatformVideoViewCreationParams ()
+ (PlatformVideoViewCreationParams *)fromList:(NSArray<id> *)list;
+ (nullable PlatformVideoViewCreationParams *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface VideoPlayerOptions ()
+ (VideoPlayerOptions *)fromList:(NSArray<id> *)list;
+ (nullable VideoPlayerOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface CreateMessage ()
+ (CreateMessage *)fromList:(NSArray<id> *)list;
+ (nullable CreateMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation PlatformVideoViewCreationParams
+ (instancetype)makeWithPlayerId:(NSInteger )playerId {
  PlatformVideoViewCreationParams* pigeonResult = [[PlatformVideoViewCreationParams alloc] init];
  pigeonResult.playerId = playerId;
  return pigeonResult;
}
+ (PlatformVideoViewCreationParams *)fromList:(NSArray<id> *)list {
  PlatformVideoViewCreationParams *pigeonResult = [[PlatformVideoViewCreationParams alloc] init];
  pigeonResult.playerId = [GetNullableObjectAtIndex(list, 0) integerValue];
  return pigeonResult;
}
+ (nullable PlatformVideoViewCreationParams *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PlatformVideoViewCreationParams fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.playerId),
  ];
}
@end

@implementation VideoPlayerOptions
+ (instancetype)makeWithMixWithOthers:(nullable NSNumber *)mixWithOthers
    allowBackgroundPlayback:(nullable NSNumber *)allowBackgroundPlayback
    minBufferMs:(nullable NSNumber *)minBufferMs
    maxBufferMs:(nullable NSNumber *)maxBufferMs
    bufferForPlaybackMs:(nullable NSNumber *)bufferForPlaybackMs
    bufferForPlaybackAfterRebufferMs:(nullable NSNumber *)bufferForPlaybackAfterRebufferMs {
  VideoPlayerOptions* pigeonResult = [[VideoPlayerOptions alloc] init];
  pigeonResult.mixWithOthers = mixWithOthers;
  pigeonResult.allowBackgroundPlayback = allowBackgroundPlayback;
  pigeonResult.minBufferMs = minBufferMs;
  pigeonResult.maxBufferMs = maxBufferMs;
  pigeonResult.bufferForPlaybackMs = bufferForPlaybackMs;
  pigeonResult.bufferForPlaybackAfterRebufferMs = bufferForPlaybackAfterRebufferMs;
  return pigeonResult;
}
+ (VideoPlayerOptions *)fromList:(NSArray<id> *)list {
  VideoPlayerOptions *pigeonResult = [[VideoPlayerOptions alloc] init];
  pigeonResult.mixWithOthers = GetNullableObjectAtIndex(list, 0);
  pigeonResult.allowBackgroundPlayback = GetNullableObjectAtIndex(list, 1);
  pigeonResult.minBufferMs = GetNullableObjectAtIndex(list, 2);
  pigeonResult.maxBufferMs = GetNullableObjectAtIndex(list, 3);
  pigeonResult.bufferForPlaybackMs = GetNullableObjectAtIndex(list, 4);
  pigeonResult.bufferForPlaybackAfterRebufferMs = GetNullableObjectAtIndex(list, 5);
  return pigeonResult;
}
+ (nullable VideoPlayerOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [VideoPlayerOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.mixWithOthers ?: [NSNull null],
    self.allowBackgroundPlayback ?: [NSNull null],
    self.minBufferMs ?: [NSNull null],
    self.maxBufferMs ?: [NSNull null],
    self.bufferForPlaybackMs ?: [NSNull null],
    self.bufferForPlaybackAfterRebufferMs ?: [NSNull null],
  ];
}
@end

@implementation CreateMessage
+ (instancetype)makeWithAsset:(nullable NSString *)asset
    uri:(nullable NSString *)uri
    packageName:(nullable NSString *)packageName
    formatHint:(nullable NSString *)formatHint
    httpHeaders:(NSDictionary<NSString *, NSString *> *)httpHeaders
    viewType:(nullable PlatformVideoViewTypeBox *)viewType
    options:(nullable VideoPlayerOptions *)options {
  CreateMessage* pigeonResult = [[CreateMessage alloc] init];
  pigeonResult.asset = asset;
  pigeonResult.uri = uri;
  pigeonResult.packageName = packageName;
  pigeonResult.formatHint = formatHint;
  pigeonResult.httpHeaders = httpHeaders;
  pigeonResult.viewType = viewType;
  pigeonResult.options = options;
  return pigeonResult;
}
+ (CreateMessage *)fromList:(NSArray<id> *)list {
  CreateMessage *pigeonResult = [[CreateMessage alloc] init];
  pigeonResult.asset = GetNullableObjectAtIndex(list, 0);
  pigeonResult.uri = GetNullableObjectAtIndex(list, 1);
  pigeonResult.packageName = GetNullableObjectAtIndex(list, 2);
  pigeonResult.formatHint = GetNullableObjectAtIndex(list, 3);
  pigeonResult.httpHeaders = GetNullableObjectAtIndex(list, 4);
  pigeonResult.viewType = GetNullableObjectAtIndex(list, 5);
  pigeonResult.options = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable CreateMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [CreateMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.asset ?: [NSNull null],
    self.uri ?: [NSNull null],
    self.packageName ?: [NSNull null],
    self.formatHint ?: [NSNull null],
    self.httpHeaders ?: [NSNull null],
    self.viewType ?: [NSNull null],
    self.options ?: [NSNull null],
  ];
}
@end

@interface nullMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation nullMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[PlatformVideoViewTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: 
      return [PlatformVideoViewCreationParams fromList:[self readValue]];
    case 131: 
      return [VideoPlayerOptions fromList:[self readValue]];
    case 132: 
      return [CreateMessage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PlatformVideoViewTypeBox class]]) {
    PlatformVideoViewTypeBox *box = (PlatformVideoViewTypeBox *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[PlatformVideoViewCreationParams class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[VideoPlayerOptions class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CreateMessage class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface nullMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullMessagesPigeonCodecReaderWriter *readerWriter = [[nullMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpAndroidVideoPlayerApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AndroidVideoPlayerApi> *api) {
  SetUpAndroidVideoPlayerApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpAndroidVideoPlayerApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<AndroidVideoPlayerApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.initialize", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initializeWithError:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(initializeWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api initializeWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.create", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createMsg:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(createMsg:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        CreateMessage *arg_msg = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api createMsg:arg_msg error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.dispose", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(disposePlayerId:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(disposePlayerId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_playerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        [api disposePlayerId:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.setLooping", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setLoopingPlayerId:looping:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(setLoopingPlayerId:looping:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_playerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        BOOL arg_looping = [GetNullableObjectAtIndex(args, 1) boolValue];
        FlutterError *error;
        [api setLoopingPlayerId:arg_playerId looping:arg_looping error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.setVolume", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setVolumePlayerId:volume:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(setVolumePlayerId:volume:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_playerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        double arg_volume = [GetNullableObjectAtIndex(args, 1) doubleValue];
        FlutterError *error;
        [api setVolumePlayerId:arg_playerId volume:arg_volume error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.setPlaybackSpeed", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setPlaybackSpeedPlayerId:speed:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(setPlaybackSpeedPlayerId:speed:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_playerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        double arg_speed = [GetNullableObjectAtIndex(args, 1) doubleValue];
        FlutterError *error;
        [api setPlaybackSpeedPlayerId:arg_playerId speed:arg_speed error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.play", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(playPlayerId:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(playPlayerId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_playerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        [api playPlayerId:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.position", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(positionPlayerId:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(positionPlayerId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_playerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        NSNumber *output = [api positionPlayerId:arg_playerId error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.seekTo", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(seekToPlayerId:position:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(seekToPlayerId:position:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_playerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        NSInteger arg_position = [GetNullableObjectAtIndex(args, 1) integerValue];
        FlutterError *error;
        [api seekToPlayerId:arg_playerId position:arg_position error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.pause", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pausePlayerId:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(pausePlayerId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSInteger arg_playerId = [GetNullableObjectAtIndex(args, 0) integerValue];
        FlutterError *error;
        [api pausePlayerId:arg_playerId error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.video_player_android.AndroidVideoPlayerApi.setMixWithOthers", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMixWithOthersMixWithOthers:error:)], @"AndroidVideoPlayerApi api (%@) doesn't respond to @selector(setMixWithOthersMixWithOthers:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        BOOL arg_mixWithOthers = [GetNullableObjectAtIndex(args, 0) boolValue];
        FlutterError *error;
        [api setMixWithOthersMixWithOthers:arg_mixWithOthers error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
